evoting/urls.py
from django.contrib import admin
from django.urls import path,include
import voting
from django.conf.urls.static import static
from django.conf import settings
from voting import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('voting/',include("voting.urls")),
    path('',views.index,name="home"),
    path('logout/',views.user_logout,name="user_logout"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.urls import path
from voting import views

app_name="voting"

urlpatterns = [
    path('register/',views.register,name="registration"),
    path('user_login/',views.user_login,name="user_login"),
    path('cast_vote/',views.cast_vote,name="cast_vote"),
]

voting/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Constituency(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name
    

class Candidate(models.Model):
    name=models.CharField(max_length=50)
    constituency=models.ForeignKey(Constituency,on_delete=models.CASCADE)
    no_votes=models.IntegerField(default=0)

    def __str__(self):
        return self.name
    

class Voter(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    is_voted=models.BooleanField(default=False)
    constituency=models.ForeignKey(Constituency,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

voting/forms.py
from django import forms
from voting.models import *

class UserForm(forms.ModelForm):
    password=forms.CharField(max_length=20,widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=('username','email','password')


class VoterForm(forms.ModelForm):
    class Meta:
        model=Voter
        fields=('constituency',)

class ConstForm(forms.ModelForm):
    class Meta:
        model=Constituency
        fields="__all__"

voting/views.py
from django.shortcuts import render
from voting.forms import *
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        user=request.user.username
        return render(request,"voting/home.html",context={"username":user})
    return redirect("voting:home.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required
def cast_vote(request):
    user=request.session.get('username')
    u=User.objects.get(username=user)
    if request.method=="POST":
        candidate_name=request.POST['cand_name']
        c=Candidate.objects.get(name=candidate_name)
        v=c.no_votes+1
        c=Candidate.objects.filter(name=candidate_name).update(no_votes=v)
       
        c=Voter.objects.filter(user=u).update(is_voted=True)
        return render(request,"voting/home.html",context={"username":user})
    else:
        v=Voter.objects.get(user=u)
        candidates=Candidate.objects.filter(constituency=v.constituency)
    return render(request,"voting/cast_vote.html",context={"candidates":candidates,"vote_status":v.is_voted})

def register(request):
    registered=False
    if request.method=="POST":
        userform=UserForm(request.POST)
        constform=VoterForm(request.POST)
        if userform.is_valid() and constform.is_valid():
            user=userform.save(commit=False)
            user.set_password(userform.cleaned_data['password'])
            user.save()

            profile=constform.save(commit=False)
            profile.user=user
            profile.save()
            registered=True
    userform=UserForm()
    constform=VoterForm()
    d={'registered':registered,'userform':userform,'constform':constform}
    return render(request,'register.html',context=d)


def user_login(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        if user and user.is_active:
            login(request,user)
            request.session['username']=username
            return HttpResponseRedirect(reverse('home'))
        else:
            return HttpResponse("Not a Active User or Invalid username and password")
    return render(request,'user_login.html',context={})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>BASE PAGE</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="nav">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-link" href="{% url 'voting:registration' %}">Registration</a>
        <a class="nav-link" href="{% url 'voting:cast_vote' %}">Voting</a>
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'voting:user_login' %}">Login</a>

        {% endif %}
        

        
    </nav>
        {% block body_block %}
          
        {% endblock  %}
    
</body>
</html>

templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  <title>Registration Page</title>
{% endblock %}

{% block body_block %}
<div class="container">
    {% if registered %}
    <div class="container">
        <div class="jumbtron">
            <h1>Thanks For Registering</h1>
        </div>
    </div>
        
    {% else %}
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{userform|crispy}}
          {{constform|crispy}}
          <input type="submit" value="Register" class="btn btn-primary">
        </form>
    </div>
  </div>
    {% endif %}
    
  
{% endblock %}

templates/user_login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  <title>Login Page</title>
{% endblock %}

{% block body_block %}
<div class="container">
   <div class="jumbotron">
        <form method="POST">
          {% csrf_token %}
          <label for="username">UserName : </label>
          <input type="text" name="username" id="username">
          <label for="password">Password : </label>
          <input type="password" name="password" id="password">
          <input type="submit" value="Login" class="btn btn-primary">
        </form>
    </div>
  </div>
  
{% endblock %}